version: "0.5"

processes:
  pre-init:
    command: 'source $PORTAL_ROOT/sh/devenv/pre-init.sh'
    namespace: pre-init

  bitcoin:
    command: bitcoind-dev
    namespace: proc
    log_location: $PLAYNET_ROOT/log/portal/bitcoind.log
    availability:
      restart: always
    depends_on:
      pre-init:
        condition: process_completed_successfully
    readiness_probe:
      exec:
        command: bitcoin-cli-dev getblockchaininfo

  geth:
    command: geth-dev --password=$PORTAL_ETHEREUM_GETH_DIR/portal-wallet-password
    namespace: proc
    log_location: $PLAYNET_ROOT/log/portal/geth.log
    availability:
      restart: always
    depends_on:
      pre-init:
        condition: process_completed_successfully
    readiness_probe:
      exec:
        command: geth-dev attach --exec eth.coinbase

  alice:
    command: lnd-alice --noseedbackup
    namespace: users
    log_location: $PLAYNET_ROOT/log/alice/lnd.log
    depends_on:
      bitcoin:
        condition: process_healthy
    readiness_probe:
      exec:
        command: lncli-alice getinfo

  bob:
    command: lnd-bob --noseedbackup
    namespace: users
    log_location: $PLAYNET_ROOT/log/bob/lnd.log
    depends_on:
      bitcoin:
        condition: process_healthy
    readiness_probe:
      exec:
        command: lncli-bob getinfo

  post-init:
    command: 'source $PORTAL_ROOT/sh/devenv/post-init.sh'
    namespace: post-init
    depends_on:
      alice:
        condition: process_healthy
      bob:
        condition: process_healthy