== Demo Instructions

This demo will guide you through the process of creating new inscriptions, performing a swap, and confirming transactions in Sparrow wallet.

=== Prerequisites

- Ensure you have a populated folder named `/inscriptions` with image files that are used to create new inscriptions.
- Get the bitcoin data directory path, this is where Bitcoin.conf file resides
- Get the path to the bitcoin-cli command
- Create an alias for bitcoin-cli command `alias bcli="/snap/bin/bitcoin-core.cli -datadir=/home/dev/snap/bitcoin-core/common/.bitcoin"`

=== Step 1: Empty Alice's Taproot Wallet

Empty Alice's wallet spending all coins and sending them to an external wallet. This step clears Alice's wallet of all inscriptions for a fresh start.


=== Step 2: Resupply Wallet

Resupply Alice's wallet with Bitcoin by mining 1 block using `generatetoaddress` command.

[source,bash]
----
# Use either of these commands to mine a block
bcli generatetoaddress 4 <address to receive block rewards>
bcli -generate -rpcwallet=<loaded wallet on bitcoin-cli> 1
----


=== Step 3: Run `inscribe.sh`

Run the `inscribe.sh` script with images in the `/inscriptions` folder to create new inscriptions to Alice's wallet.


=== Step 4: Update Collections Page

Run `updateInscriptions.sh` to update the collections page with Alice's new inscriptions.

[source,bash]
----
./updateInscriptions.sh inscriptions.json inscription_info.js
----


=== Step 5: Perform a Swap

. Alice creates an order with one of her inscriptions for 0.00004 BTC.
. Bob creates an order with 0.00004 BTC for the inscription Alice chose.
. Alice sends the inscription to the payment address.


=== Step 6: Confirm Transaction

Generate a block for the final transaction to confirm.


=== Step 7: Update Alice's Inscription Collection

Run `watchInscriptions.sh` to update Alice's inscription collection.

[source,bash]
----
./watchInscriptions.sh
----

=== Step 8: Confirm Swap has completed

Check Sparrow wallet for Bob's taproot wallet to confirm Alice's ordinal inscription was received, and
Check Alice and Bob's lightning channel to see the destination balance has increased, Alice as the destination balance.
