name: Pull Request

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  DEPLOY_HOST: node.playnet.portaldefi.zone

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]
        # os: [ubuntu-latest]
        # os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-22.05
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"

    - name: Setup binary cache
      uses: cachix/cachix-action@v12
      with:
        name: portaldefi-demo
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Install direnv
      uses: HatsuneMiku3939/direnv-action@v1
      with:
        direnvVersion: 2.32.1

    # - name: Load environment with direnv
    #   run: direnv allow

    - name: Install Chrome for integration tests
      run: direnv exec . npx @puppeteer/browsers install $PUPPETEER_CHROME_FLAVOR@$PUPPETEER_CHROME_VERSION

    - name: Start devenv
      run: direnv exec . devenv up --watch 

    - name: Run unit tests
      run: direnv exec . tests unit

    - name: Run nixos tests
      run: direnv exec . tests nixos
      if: matrix.os == 'ubuntu-latest'

    - name: Build PortalDefi packages
      run: nix-build --option sandbox false --attr packages
      if: matrix.os == 'ubuntu-latest'

    # TODO: Find a proper way of packaging properly playnet state directly inside a nix derivation (that means contracts.json needs to be produced outside)
    - uses: actions/upload-artifact@v3
      if: matrix.os != 'macOS-latest'
      with:
        name: playnet
        path: |
          playnet/
          !playnet/**/*.ipc

  deploy:
    needs: build
    runs-on: [ubuntu-latest]
    if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
    # if: true
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-22.05
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"

    - name: Setup binary cache
      uses: cachix/cachix-action@v12
      with:
        name: portaldefi-demo
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    # TODO: Find a proper way of packaging properly playnet state directly inside a nix derivation (that means contracts.json needs to be produced outside)
    - uses: actions/download-artifact@v3
      with:
        name: playnet
        path: playnet/

    - name: Build PortalOS closure
      run: |
        system_path=$(nix-build --option sandbox false --attr nixosConfigurations.portalos)
        echo "SYSTEM_PATH=$system_path" > $GITHUB_OUTPUT
      id: build-machine-closure

    - name: Setup NixOS deploy env
      run: |
        ssh_key=$(mktemp)
        chmod 600 $ssh_key
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > $ssh_key
        echo "SSH_KEY_PATH=$ssh_key" > $GITHUB_OUTPUT
      id: deploy_env

    - name: Deploy closure on node.playnet.portaldefi.zone
      run: |
        echo "Copying nixos closure to machine"
        nix copy -s --to "ssh://$DEPLOY_HOST" $SYSTEM_PATH
        echo "Switching to new nixos closure"
        ssh $NIX_SSHOPTS "$DEPLOY_HOST" "$SYSTEM_PATH"/bin/switch-to-configuration switch
        echo "Removing unused packages"
        ssh $NIX_SSHOPTS "$DEPLOY_HOST" nix-collect-garbage
      env:
        SSH_KEYFILE: ${{ steps.deploy_env.outputs.SSH_KEY_PATH }}
        SYSTEM_PATH: ${{ steps.build-machine-closure.outputs.SYSTEM_PATH }}
        NIX_SSHOPTS: "-o StrictHostKeyChecking=no -i ${{ steps.deploy_env.outputs.SSH_KEY_PATH }} -l root"
