name: Nix

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-22.05

    - name: Setup binary cache
      uses: cachix/cachix-action@v10
      with:
        name: portaldefi-demo
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build PortalDefi packages
      run: nix-build nix -A portaldefi
