name: Test

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        node-version: [16.x]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: checkout branch
      uses: actions/checkout@v3

    - name: setup cachix on ${{ matrix.os }}
      uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-22.05

    - name: run tests
      run: nix-shell --run "cd js/portal && npm ci && npm test"

    - name: upload to build cache
      uses: cachix/cachix-action@v10
      with:
        name: portaldefi-demo
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
